Repository HOP-3-Duluu/School_Vibes, pull requests merged in 2023-05, with the labels that each got.

#39 [backend] initialization
  backend/.gitignore
  backend/README.md
  backend/handler.ts
  backend/package-lock.json
  backend/package.json
  backend/serverless.yml
Labels: enhancement

#41 [screen] onBoarding
  School_Vibes/ios/Podfile.lock
  School_Vibes/package-lock.json
  School_Vibes/package.json
  School_Vibes/src/assets/images/onBoarding1.png
  School_Vibes/src/assets/images/onBoarding2.png
  School_Vibes/src/assets/images/onBoarding3.png
  School_Vibes/src/components/core/Text.tsx
  School_Vibes/src/index.tsx
  School_Vibes/src/navigations/BottomNavigation.tsx
  School_Vibes/src/screens/Welcome.tsx
  School_Vibes/src/screens/index.ts
  School_Vibes/yarn.lock
Labels: enhancement

#45 [component] Tabs
  School_Vibes/src/Check.tsx
  School_Vibes/src/components/core/Tabs.tsx
  School_Vibes/src/components/core/index.ts
Labels: enhancement

#47 TaskBox
  School_Vibes/src/Check.tsx
  School_Vibes/src/assets/icon/Calendar.tsx
  School_Vibes/src/components/common/TaskBox.tsx
  School_Vibes/src/components/common/index.ts
Labels: enhancement

#49 [backend] CRUD
  backend/.build/handler.js
  backend/.build/handler.js.map
  backend/.build/package.json
  backend/handler.ts
  backend/package.json
  backend/serverless.yml
  backend/src/Group/create.ts
  backend/src/Group/delete.ts
  backend/src/Group/get.ts
  backend/src/Group/update.ts
  backend/src/lib/constant.ts
  backend/src/lib/database.ts
  backend/src/lib/s3.ts
  backend/src/lib/sqs.ts
  backend/yarn.lock
Labels: enhancement

#52 [backend] create CRUD in class, group, user
  backend/src/Group/create.ts
  backend/src/Group/delete.ts
  backend/src/Group/get.ts
  backend/src/Group/update.ts
  backend/src/controller/Class.ts
  backend/src/controller/Group.ts
  backend/src/controller/User.ts
  backend/src/models/Class.ts
  backend/src/models/Groups.ts
  backend/src/models/User.ts
Labels: enhancement

#54 [API] CRUD
  School_Vibes/package.json
  School_Vibes/src/library/axios.ts
  School_Vibes/src/library/index.ts
  School_Vibes/src/providers/AuthProvider.tsx
  School_Vibes/src/providers/DataProvider.tsx
  School_Vibes/yarn.lock
Labels: enhancement

#43 [component] Input
  School_Vibes/package.json
  School_Vibes/src/assets/icon/Calendar.tsx
  School_Vibes/src/assets/icon/Home.tsx
  School_Vibes/src/assets/icon/Profile.tsx
  School_Vibes/src/assets/icon/Task.tsx
  School_Vibes/src/components/core/Input.tsx
  School_Vibes/src/components/core/index.ts
  School_Vibes/src/navigations/TabNavigation.tsx
  School_Vibes/yarn.lock
Labels: enhancement

#58 [navigations] Stack
  School_Vibes/src/Check.tsx
  School_Vibes/src/components/common/TaskBox.tsx
  School_Vibes/src/navigations/RootNavigation.tsx
  School_Vibes/src/screens/GroupDetail.tsx
  School_Vibes/src/screens/LessonDetail.tsx
  School_Vibes/src/screens/Welcome.tsx
  School_Vibes/src/screens/index.ts
Labels: enhancement

#64 statistic box done-48
  School_Vibes/babel.config.js
  School_Vibes/ios/Podfile.lock
  School_Vibes/ios/School_Vibes.xcodeproj/project.pbxproj
  School_Vibes/package-lock.json
  School_Vibes/package.json
  School_Vibes/src/Check.tsx
  School_Vibes/src/assets/icon/Correct.tsx
  School_Vibes/src/assets/icon/index.ts
  School_Vibes/src/components/common/StatisticBox.tsx
  School_Vibes/src/components/common/index.ts
  School_Vibes/tsconfig.json
  School_Vibes/yarn.lock
  package-lock.json
Labels: enhancement

#66 [screen] Login
  School_Vibes/src/Check.tsx
  School_Vibes/src/assets/icon/Email.tsx
  School_Vibes/src/assets/icon/Password.tsx
  School_Vibes/src/assets/icon/index.ts
  School_Vibes/src/assets/images/ArtWork.tsx
  School_Vibes/src/components/core/Input.tsx
  School_Vibes/src/interfaces/index.ts
  School_Vibes/src/navigations/RootNavigation.tsx
  School_Vibes/src/screens/Login.tsx
  School_Vibes/src/screens/Welcome.tsx
  School_Vibes/src/screens/index.ts
Labels: enhancement

#65 56 common Task Tick Box
  School_Vibes/src/assets/icon/Edit.tsx
  School_Vibes/src/assets/icon/More.tsx
  School_Vibes/src/assets/icon/Profile.tsx
  School_Vibes/src/assets/icon/Trash.tsx
  School_Vibes/src/components/common/TickBox.tsx
  School_Vibes/src/components/common/index.ts
  School_Vibes/src/screens/Task.tsx
  School_Vibes/yarn.lock
Labels: enhancement

#73 [screen] Notifications
  .idea/.gitignore
  .idea/Demoday.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  School_Vibes/src/components/common/NotificationCard.tsx
  School_Vibes/src/components/common/TickBox.tsx
  School_Vibes/src/components/common/index.ts
  School_Vibes/src/layouts/Header.tsx
  School_Vibes/src/layouts/index.ts
  School_Vibes/src/navigations/RootNavigation.tsx
  School_Vibes/src/navigations/TabNavigation.tsx
  School_Vibes/src/screens/AddScreen.tsx
  School_Vibes/src/screens/Home.tsx
  School_Vibes/src/screens/Login.tsx
  School_Vibes/src/screens/Notifications.tsx
  School_Vibes/src/screens/index.ts
Labels: enhancement

#77 [fix]
  School_Vibes/src/components/common/Calendar.tsx
  School_Vibes/src/components/common/TaskBox.tsx
  School_Vibes/src/navigations/RootNavigation.tsx
  School_Vibes/src/screens/Home.tsx
  School_Vibes/src/screens/LessonDetail.tsx
  School_Vibes/src/screens/Login.tsx
  School_Vibes/src/screens/Task.tsx
  School_Vibes/src/screens/Welcome.tsx
  package-lock.json
Labels: bug

#79 [screen] Add
  School_Vibes/ios/Podfile.lock
  School_Vibes/ios/School_Vibes.xcodeproj/project.pbxproj
  School_Vibes/package-lock.json
  School_Vibes/package.json
  School_Vibes/src/animation/loadging.json
  School_Vibes/src/assets/icon/Attachment.tsx
  School_Vibes/src/assets/icon/BulletLeft.tsx
  School_Vibes/src/assets/icon/Close.tsx
  School_Vibes/src/assets/icon/Left.tsx
  School_Vibes/src/assets/icon/Right.tsx
  School_Vibes/src/assets/icon/index.ts
  School_Vibes/src/components/common/NotificationCard.tsx
  School_Vibes/src/navigations/RootNavigation.tsx
  School_Vibes/src/navigations/TabNavigation.tsx
  School_Vibes/src/screens/AddScreen.tsx
  School_Vibes/src/screens/JoinScreen.tsx
  School_Vibes/src/screens/Notifications.tsx
  School_Vibes/src/screens/Task.tsx
  School_Vibes/src/screens/index.ts
  School_Vibes/yarn.lock
Labels: enhancement

#81 [screen] Profile
  School_Vibes/src/assets/icon/Notifications.tsx
  School_Vibes/src/assets/icon/index.ts
  School_Vibes/src/assets/images/Logo.png
  School_Vibes/src/components/common/TickBox.tsx
  School_Vibes/src/navigations/RootNavigation.tsx
  School_Vibes/src/screens/GroupDetail.tsx
  School_Vibes/src/screens/LessonDetail.tsx
  School_Vibes/src/screens/Profile.tsx
Labels: enhancement

#83 [fix] lottie && addScreen
  School_Vibes/ios/Podfile.lock
  School_Vibes/package.json
  School_Vibes/src/assets/icon/Close.tsx
  School_Vibes/src/components/common/AutoComplete.tsx
  School_Vibes/src/components/common/Calendar.tsx
  School_Vibes/src/components/common/StatisticBox.tsx
  School_Vibes/src/components/common/TickBox.tsx
  School_Vibes/src/components/common/Time.tsx
  School_Vibes/src/components/common/index.ts
  School_Vibes/src/components/core/Modal.tsx
  School_Vibes/src/components/core/Stack.tsx
  School_Vibes/src/components/core/Tabs.tsx
  School_Vibes/src/components/core/index.ts
  School_Vibes/src/navigations/RootNavigation.tsx
  School_Vibes/src/navigations/TabNavigation.tsx
  School_Vibes/src/screens/AddScreen.tsx
  School_Vibes/src/screens/Home.tsx
  School_Vibes/src/screens/Profile.tsx
  School_Vibes/src/screens/Task.tsx
  School_Vibes/yarn.lock
Labels: bug, enhancement

#86 Profile
  School_Vibes/ios/Podfile.lock
  School_Vibes/package-lock.json
  School_Vibes/src/assets/icon/Logo.tsx
  School_Vibes/src/assets/icon/Logout.tsx
  School_Vibes/src/assets/icon/Phone.tsx
  School_Vibes/src/assets/icon/PrivacyPolicy.tsx
  School_Vibes/src/assets/icon/TermsCond.tsx
  School_Vibes/src/assets/icon/index.ts
  School_Vibes/src/navigations/RootNavigation.tsx
  School_Vibes/src/screens/Profile.tsx
  School_Vibes/yarn.lock
Labels: enhancement

#87 Group Card
  School_Vibes/ios/Podfile.lock
  School_Vibes/package-lock.json
  School_Vibes/package.json
  School_Vibes/src/components/common/GroupCard.tsx
  School_Vibes/src/components/common/index.ts
  School_Vibes/src/components/core/Stack.tsx
  School_Vibes/src/screens/Home.tsx
  School_Vibes/yarn.lock
Labels: enhancement

#89 [component] Gesture
  School_Vibes/package.json
  School_Vibes/src/components/common/Calendar.tsx
  School_Vibes/yarn.lock
Labels: bug, documentation, enhancement

#93 [component] Create or join
  School_Vibes/src/components/core/Input.tsx
  School_Vibes/src/providers/AuthProvider.tsx
  School_Vibes/src/screens/Home.tsx
  backend/.build/src/controller/group.js
  backend/.build/src/controller/user.js
  backend/.build/src/models/User.js
  backend/.build/src/models/group.js
  backend/serverless.yml
  backend/src/controller/Group.ts
  backend/src/controller/User.ts
  backend/src/models/User.ts
  backend/src/models/group.ts
Labels: enhancement
